services:
  http.error_handler:
    class: Glassy::HTTP::ErrorHandler

  http.kernel:
    class: Glassy::HTTP::Kernel
    kwargs:
      error_handler: '@http_error_handler'

  http.server_run_command:
    class: Glassy::HTTP::Command::ServerRunCommand
    kwargs:
      input: '@console_input'
      output: '@console_output'
      container: '@container'
      http_kernel: '@http_kernel'
    tag:
      - console.command

tags:
  http.controller:
    restriction: Glassy::HTTP::Controller

  http.middleware:
    restriction: Glassy::HTTP::Middleware
