services:
  server_run:
    class: Glassy::HTTP::Command::ServerRunCommand
    kwargs:
      input: '@console_input'
      output: '@console_output'
      container: '@container'
    tag:
      - command

tags:
  controller:
    restriction: Glassy::HTTP::Controller
